helm_configuration:
  frequency: 10.0

finite_state_machine:
  - name: start
    mode: idle
    initial: true
    transitions:
      - survey_local
      - kill

  - name: survey_local
    mode: flight
    transitions:
      - start
      - kill

  - name: kill
    mode: idle
    transition:
      - start


behaviors:
  - name: path_local
    plugin: helm::PathFollowing
    states:
      - { name: survey_local, priority: 1 }

  - name: depth_tracking
    plugin: helm::DepthTracking
    states:
      - { name: survey_local, priority: 1 }

  - name: periodic_sufacing
    plugin: helm::PeriodicSurface
    states:
      - {name: survey_local, priority: 2 }
